const ko = {
  title: '하루의 긍정적 회고가 다음 날 자기효능감에 미치는 영향',
  subtitle: '대학생의 14일 일상기록을 위한 문헌고찰 및 단일집단 반복측정 연구계획',
  pages: [
    {type:'cover'},
    {h:'초록', p:[`본 연구는 하루의 긍정적 회고(그날 잘된 일과 그 이유를 기록하는 활동)가 다음 날의 상태 자기효능감에 미치는 단기적 관련성을 검토하기 위한 문헌고찰 및 연구계획이다. 긍정적 심리중재는 안녕감 향상과 우울 증상 감소에 작은 수준의 평균 효과를 보였으나, 개인 수준에서 어떤 날에 어떤 방식으로 작동하는지에 관한 검증은 상대적으로 부족하다. 특히 ‘좋았던 일’을 단순히 나열하는 것과 그 일이 가능했던 자신의 행동·환경·관계를 해석하는 과정은 구분될 필요가 있다.`, `이에 본 연구는 18세 이상 대학생 20명을 대상으로 14일간 모바일 기록을 수집하는 반복측정 설계를 제안한다. 참가자는 매일 밤 긍정적 사건 세 가지와 원인을 기록하고, 다음 날 아침 과업수행 자신감과 정서를 0–10점으로 보고한다. 주 분석은 개인 내 변동을 반영하는 다층모형이며, 회고의 시행 여부·구체성·자기 기여 인식이 다음 날 자기효능감을 예측하는지 검토한다.`, `본 문서는 실제 결과를 보고하지 않는다. 데이터 수집 전에는 효과의 방향이나 크기를 단정할 수 없기 때문이다. 대신 재현 가능한 절차, 측정도구, 분석계획, 윤리 기준 및 앱 구현 요건을 명시해 이후의 실증연구와 최소기능 제품(MVP)이 같은 근거 위에서 발전하도록 한다.`]},
    {h:'핵심어와 연구의 위치', p:[`핵심어: 긍정적 회고, 세 가지 좋은 일, 감사, 자기효능감, 일상기록, 반복측정, 디지털 정신건강. 본 연구의 목적은 진단·치료를 대체하는 정신건강 앱을 만드는 데 있지 않다. 일상적 자기관찰을 돕는 저위험 기록 도구의 근거를 탐색하는 데 있다.`, `자기효능감은 특정 상황에서 필요한 행동을 성공적으로 해낼 수 있다는 자신의 판단을 뜻한다(Bandura, 1997). 이는 일반적인 ‘기분이 좋다’와 다르며, 행동 선택·노력·지속성에 연결되는 인지적 기대다. 따라서 본 연구는 주관적 안녕감만으로 결론을 내리지 않고 다음 날의 구체적 과업수행 자신감을 1차 결과로 둔다.`, `긍정적 회고는 좋았던 사실만 되뇌는 낙관주의와도 다르다. 사건, 맥락, 자신의 기여, 타인의 도움을 짧게 언어화하는 구조화된 기록으로 정의한다. 이 정의는 긍정 경험의 주의 배분과 의미 부여라는 두 과정을 함께 포착하려는 선택이다.`]},
    {h:'1. 연구 배경', p:[`일상에서 부정적 사건은 주의를 더 강하게 끌고, 반복적 반추는 정서 회복과 행동 개시를 방해할 수 있다. 반대로 긍정적 사건에 주의를 기울이고 이를 해석하는 활동은 정서적 자원을 넓히고 회복을 도울 가능성이 제기되어 왔다. Fredrickson(2001)의 확장-구축 이론은 긍정 정서가 순간적 쾌감에 그치지 않고 사고·행동의 선택지를 확장해 지속 가능한 자원을 축적할 수 있다고 설명한다.`, `그러나 ‘긍정적으로 생각하라’는 조언은 연구 질문이 될 수 없다. 누가, 얼마나 자주, 무엇을 기록하고, 무엇이 달라지는지를 관찰 가능하게 정해야 한다. 본 연구는 취침 전 3분 내외의 회고와 다음 날 아침의 자기효능감 사이의 시간적 순서를 명시함으로써 이 문제를 다룬다.`, `대학생은 과제, 사회관계, 수면 변화가 빠르게 교차하는 집단이며, 짧고 반복 가능한 모바일 기록에 적합하다. 다만 본 설계의 표본은 대표 표본이 아니므로 전체 대학생이나 임상집단으로 일반화하지 않는다.`]},
    {h:'2. 선행연구: 감사와 긍정심리중재', p:[`Emmons와 McCullough(2003)는 감사한 일, 번거로움, 중립 사건을 기록하도록 한 여러 연구에서 감사 조건의 안녕감 지표가 일부 비교 조건보다 높았다고 보고했다. 이 연구는 기록 활동을 무작위 조건으로 다루었다는 점에서 중요하지만, 모든 결과가 같은 방향으로 변한 것은 아니며 표본·기간·비교 조건에 따라 해석 범위가 달라진다.`, `Seligman 등(2005)은 온라인 무작위 연구에서 ‘세 가지 좋은 일’과 강점 활용 같은 긍정심리중재를 시험했다. 해당 연구는 짧은 자기보고 중재도 실험적으로 검토할 수 있음을 보여 주었다. 이후 Sin과 Lyubomirsky(2009)의 메타분석은 다양한 긍정심리중재가 안녕감과 우울에 평균적으로 유의한 효과를 보인다고 종합했지만, 중재 유형과 연구 질의 이질성이 크다는 점도 함께 고려해야 한다.`, `즉, 기존 증거는 긍정적 기록이 유망하다는 근거이지 모든 개인에게 동일한 효과가 난다는 보증은 아니다. 본 연구는 평균 효과 재현보다 ‘같은 사람에게 회고가 더 충실했던 날 다음 날 무엇이 달라지는가’라는 개인 내 질문을 우선한다.`]},
    {h:'3. 선행연구: 자기효능감과 반성', p:[`Bandura(1997)는 성공 경험, 대리 경험, 언어적 설득, 생리·정서 상태를 자기효능감의 주요 정보원으로 제시했다. 긍정적 회고는 이미 있었던 작은 성공 경험을 회상하고, 그 원인을 행동과 연결해 해석하게 함으로써 첫 번째 정보원을 더 쉽게 접근하게 할 수 있다. 이것은 인과기제에 관한 가설이며, 기록 자체가 성공을 만들어 낸다는 뜻은 아니다.`, `반성적 글쓰기는 경험을 단순 저장하는 행위가 아니라 경험의 의미를 구성하는 과정이 될 수 있다. 다만 자유서술은 부담이 크고, 과도한 자기평가는 오히려 반추가 될 수 있다. 따라서 앱의 질문은 ‘잘한 일 3개’에 더해 ‘무엇이 가능하게 했나?’를 묻되, 평가·비교·점수 경쟁을 유도하지 않도록 설계한다.`, `본 연구에서 자기효능감은 매일의 상태(state) 수준으로 측정한다. 고정된 성격 특성처럼 다루는 대신, 다음 날의 중요한 과제 한 가지를 정하고 그것을 시작·지속·마무리할 자신감을 묻는다. 이 선택은 앱이 제공할 피드백과 측정개념의 거리를 줄인다.`]},
    {h:'4. 개념모형과 연구문제', p:[`개념모형은 ‘저녁의 긍정적 회고 → 긍정 경험의 접근성 및 자기 기여 인식 → 다음 날 아침의 과업수행 자기효능감’이다. 전날 정서와 과제 난이도는 회고와 다음 날 자신감 모두에 영향을 줄 수 있으므로, 매일 함께 기록해 통제변수로 사용한다. 수면 시간은 탐색적 공변량으로 둔다.`, `연구문제 1: 긍정적 회고를 시행한 날의 다음 날 자기효능감은 시행하지 않은 날보다 높은가? 연구문제 2: 회고의 구체성 및 자기 기여 인식은 다음 날 자기효능감과 관련되는가? 연구문제 3: 이 관련성은 전날 정서, 과제 난이도, 수면시간을 고려한 뒤에도 관찰되는가?`, `주가설(H1)은 ‘동일 참가자 내에서, 긍정적 회고를 한 날 다음 날의 상태 자기효능감은 회고하지 않은 날보다 높다’이다. 반증 가능성도 명시한다. 계수가 0에 가깝거나 음수이거나, 신뢰구간이 실질적 차이를 뒷받침하지 않으면 H1은 지지되지 않는다.`]},
    {h:'5. 연구설계', p:[`설계는 14일 단일집단 반복측정 관찰연구다. 모든 참가자가 동일한 회고 과제를 수행하되 실제 생활에서 발생하는 미시적 변동을 기록한다. 인과효과를 강하게 주장하려면 무작위 대조 설계가 더 적합하지만, 본 연구의 목표는 앱 개발 전 측정 가능성·순응도·개인 내 연관성을 확인하는 것이다.`, `참가자는 18세 이상 대학생 20명을 목표로 편의표집한다. 포함 기준은 한국어로 짧은 기록을 작성할 수 있고 스마트폰으로 아침·저녁 설문에 접근할 수 있는 사람이다. 심각한 정신건강 위기 여부를 선별하거나 치료를 제공하는 연구가 아니며, 위기 표현이 나타날 경우 자동화된 앱이 대응하지 않고 지역 긴급·상담 자원을 안내한다.`, `각 참가자는 1일차 저녁부터 14일차 저녁까지 회고를 한다. 다음 날 아침 설문은 총 14회다. 최소 10일 이상의 아침·저녁 짝 자료를 완료한 참여자만 주 분석에 포함하며, 결측은 임의로 보충하지 않고 패턴을 보고한다.`]},
    {h:'6. 절차와 측정', p:[`저녁 20:00–02:00 사이, 앱은 ‘오늘 잘된 일 또는 감사했던 일 세 가지’를 각각 10자 이상 쓰도록 요청한다. 각 항목 뒤에는 ‘이 일이 가능했던 이유는 무엇인가?’라는 짧은 후속 질문을 둔다. 참여자는 원하면 ‘타인의 도움’, ‘내 행동’, ‘상황/운’ 태그를 복수 선택할 수 있다. 완료 시간과 항목 수는 자동 기록한다.`, `다음 날 05:00–12:00 사이, 참여자는 그날의 가장 중요한 과제 한 가지를 자유롭게 적고 “이 과제를 시작하고 필요한 노력을 계속할 자신이 있다”에 0(전혀 없다)–10(매우 높다)으로 응답한다. 긍정·부정 정서는 각각 0–10으로, 예상 과제 난이도는 0–10으로, 전날 수면시간은 시간·분으로 기록한다.`, `1차 결과는 다음 날 상태 자기효능감이다. 2차 탐색 결과는 긍정 정서, 과제 시작 여부(저녁 자기보고), 기록 순응도다. 단일 문항은 응답 부담을 낮추지만 신뢰도 추정이 제한되므로, 본 연구에서는 간단한 실행지표로 사용한다는 한계를 분명히 한다.`]},
    {h:'7. 데이터 관리와 분석계획', p:[`원자료는 참여자 식별자를 무작위 코드로 치환한 CSV로 저장한다. 이름, 전화번호, 정밀 위치, 원문 중 불필요한 제3자 식별정보는 수집하지 않는다. 텍스트 원문은 연구 종료 후 익명화 검토를 거쳐 별도 암호화 보관하며, 분석용 파일에는 문자 수·태그·사전 정의한 구체성 등급만 남긴다.`, `분석 전, 회고 시행 여부는 항목 3개 중 2개 이상 작성으로 정의한다. 구체성은 사전 코드북에 따라 0(추상적 평가), 1(구체적 사건), 2(사건과 원인 연결)으로 두 명의 코더가 독립 평가하고 일치도를 보고한다. 분석자는 결과를 보기 전에 코드북과 모형식을 고정한다.`, `주 모형은 다음 날 자기효능감을 종속변수로 하는 선형혼합모형이다. 참가자별 임의 절편을 포함하고, 전날 회고 여부·개인 평균으로부터의 회고 충실도·전날 정서·과제 난이도·수면시간을 고정효과로 둔다. 표본이 작으므로 p값만으로 결론 내리지 않고 계수, 95% 신뢰구간, 개인별 궤적을 함께 제시한다.`]},
    {h:'8. 결과 제시의 사전 형식', p:[`실제 데이터 수집 전이므로 이 장에는 결과를 채우지 않는다. 아래 표는 수집 후 채울 형식이며, 빈칸이나 예시 숫자를 실제 결과처럼 제시하지 않는다. 투명성은 ‘좋은 결과’보다 결과가 어디서 왔는지 추적할 수 있게 하는 데 있다.`, `<div class="table-wrap"><table><thead><tr><th>지표</th><th>보고 방식</th><th>해석 기준</th></tr></thead><tbody><tr><td>순응도</td><td>완료 일수 / 요청 일수</td><td>14일 실행 가능성</td></tr><tr><td>자기효능감</td><td>개인별 평균·범위·시계열</td><td>개인 내 변동</td></tr><tr><td>회고–효능감 계수</td><td>혼합모형 계수와 95% CI</td><td>방향·정밀도</td></tr><tr><td>결측</td><td>시점별 건수와 이유</td><td>편향 가능성</td></tr></tbody></table></div>`, `분석 결과가 H1을 지지하지 않더라도, 회고의 부담·시간대·과제 난이도와의 관계를 기술한다. 예컨대 순응도가 낮다면 “효과 없음”보다 먼저 기록 경험의 마찰을 검토해야 한다. 반대로 연관성이 관찰되어도 무작위 배정이 아니므로 회고가 원인이라고 단정하지 않는다.`]},
    {h:'9. 윤리와 위험 관리', p:[`긍정적 회고는 저위험 활동으로 보일 수 있지만, 힘든 날에는 ‘좋은 일을 반드시 찾아야 한다’는 압박을 만들 수 있다. 따라서 건너뛰기 버튼과 “오늘은 기록하지 않아도 괜찮습니다”라는 중립적 안내를 기본으로 제공한다. 연속 미기록에 대한 알림은 하루 한 번을 넘지 않으며, 점수·연속기록·타인 순위로 참여를 압박하지 않는다.`, `동의 화면에는 연구 목적, 수집 항목, 보관 기간, 철회 방법, 앱이 의료적 진단이나 위기 대응 서비스가 아니라는 사실을 평이한 언어로 적는다. 참여자가 자해·타해의 즉각적 위험을 표현하면 자동 응답만으로 해결하려 하지 않고, 긴급 상황에서는 지역 응급서비스 이용을 권하는 문구와 상담기관 정보를 보여 준다.`, `텍스트 데이터는 특히 민감할 수 있다. 앱 개발 단계에서는 기본적으로 기기 내 저장을 우선하고, 서버 동기화는 명시적 동의와 암호화·삭제 기능이 갖춰진 뒤에만 도입한다. AI 요약 기능을 추가할 경우에도 원문을 외부 모델에 보내는지, 사용자가 어떤 선택권을 갖는지 명확히 고지해야 한다.`]},
    {h:'10. 앱으로의 전환 설계', p:[`논문에서 앱으로 넘어갈 때 핵심은 ‘좋은 말을 해 주는 챗봇’이 아니라 측정된 연구 절차를 손상하지 않는 기록 흐름이다. 첫 화면은 오늘의 기록 여부, 저녁 회고 버튼, 다음 날 아침 체크인만 보여 준다. 사용자는 3개의 사건과 원인을 기록하고, 다음 날 한 가지 과제와 자신감을 남긴다.`, `초기 MVP의 기능은 다섯 가지면 충분하다: (1) 저녁 회고 입력, (2) 아침 자기효능감 슬라이더, (3) 기기 내 주간 추세 그래프, (4) CSV 내보내기, (5) 언어 전환. 그래프는 ‘회고가 당신을 더 행복하게 만들었다’고 해석하지 않고, 기록일·응답값·결측을 사실 그대로 보여 준다.`, `AI 기능은 후순위다. 넣는다면 감정 진단이나 조언 대신 사용자가 쓴 문장을 삭제하지 않는 범위에서 태그 후보를 제안하는 보조 기능으로 제한한다. 모든 자동 분류는 수정·거부 가능해야 하며, 연구용 데이터와 개인 일기 데이터의 경계를 사용자가 선택할 수 있어야 한다.`]},
    {h:'11. 기대 기여와 한계', p:[`학문적 기여는 긍정심리중재의 평균적 효과를 재주장하는 데 있지 않다. 짧은 모바일 회고를 상태 자기효능감과 시간 순서로 연결하고, 순응도·구체성·결측을 함께 보고하는 재현 가능한 소규모 프로토콜을 제공하는 데 있다. 실무적으로는 과도한 치료 주장을 피하는 자기기록 앱의 최소 요건을 제시한다.`, `한계는 명확하다. 편의표집과 작은 표본 때문에 추정의 불확실성이 크고, 자기보고는 공통방법 편향에 취약하다. 관찰 설계는 역인과와 제3변수의 가능성을 제거하지 못하며, 단일 문항은 측정의 폭을 제한한다. 회고의 내용은 문화·언어·개인 성향에 따라 다르게 해석될 수 있다.`, `후속 연구에서는 회고 프롬프트(사건만 기록 / 원인까지 기록)를 무작위로 교차 배정하고, 과제 시작의 타임스탬프 같은 행동지표를 추가할 수 있다. 그때도 앱의 사용 지속률과 심리적 부담을 효과지표와 동등하게 보고해야 한다.`]},
    {h:'12. 결론', p:[`긍정적 회고는 간단해 보이지만, 앱과 논문 모두에서 중요한 것은 ‘긍정’이라는 포괄적 표어가 아니라 관찰 가능한 행동과 절제된 해석이다. 본 연구는 하루의 좋은 경험을 사건과 원인으로 기록하는 활동이 다음 날의 과업수행 자신감과 어떻게 함께 움직이는지 검토하도록 설계되었다.`, `현재 단계에서 정직한 결론은 효과가 있다는 것이 아니라, 효과를 확인할 수 있는 질문·측정·분석·안전장치를 마련했다는 것이다. 실제 데이터가 수집된 후에만 가설 지지 여부를 판단할 수 있다. 이 원칙은 연구의 신뢰성을 지키는 동시에, 사용자의 삶을 과장된 약속으로 다루지 않는 앱 설계의 기준이 된다.`]},
    {h:'참고문헌', p:[`아래 문헌은 제목·저자·연도·출처 및 DOI/공식 데이터베이스를 대조하여 확인한 항목이다. 웹판 링크는 원문 또는 서지 확인용이며, 모든 연구 결과의 일반화를 뜻하지 않는다.`], refs:[`Bandura, A. (1997). <i>Self-efficacy: The exercise of control.</i> W. H. Freeman.`,`Emmons, R. A., & McCullough, M. E. (2003). Counting blessings versus burdens: An experimental investigation of gratitude and subjective well-being in daily life. <i>Journal of Personality and Social Psychology, 84</i>(2), 377–389. https://doi.org/10.1037/0022-3514.84.2.377`,`Fredrickson, B. L. (2001). The role of positive emotions in positive psychology: The broaden-and-build theory of positive emotions. <i>American Psychologist, 56</i>(3), 218–226. https://doi.org/10.1037/0003-066X.56.3.218`,`Koyama, T., et al. (2022). Effectiveness of unguided internet-based cognitive behavioral therapy and the Three Good Things exercise for insomnia: 3-arm randomized controlled trial. <i>Journal of Medical Internet Research, 24</i>(2), e29247. https://doi.org/10.2196/29247`,`Seligman, M. E. P., Steen, T. A., Park, N., & Peterson, C. (2005). Positive psychology progress: Empirical validation of interventions. <i>American Psychologist, 60</i>(5), 410–421. https://doi.org/10.1037/0003-066X.60.5.410`,`Sin, N. L., & Lyubomirsky, S. (2009). Enhancing well-being and alleviating depressive symptoms with positive psychology interventions: A practice-friendly meta-analysis. <i>Journal of Clinical Psychology, 65</i>(5), 467–487. https://doi.org/10.1002/jclp.20593`,`Wood, A. M., Froh, J. J., & Geraghty, A. W. A. (2010). Gratitude and well-being: A review and theoretical integration. <i>Clinical Psychology Review, 30</i>(7), 890–905. https://doi.org/10.1016/j.cpr.2010.03.005`]},
    {h:'부록 A. 재현 패키지 안내', p:[`재현 패키지에는 (1) 익명화된 원자료 CSV, (2) 데이터 사전, (3) 분석 스크립트, (4) 코드북, (5) 본문 PDF, (6) 변경 기록을 포함한다. 원자료의 한 행은 한 참가자의 한 시점을 뜻하며 participant_id, date, evening_completed, item_count, specificity_score, self_attribution, morning_efficacy, positive_affect, negative_affect, task_difficulty, sleep_minutes, missing_reason을 권장 열로 둔다.`, `검증자는 README의 순서대로 익명화된 CSV와 분석 스크립트를 같은 폴더에 두고 실행해 표 1과 그림 1을 재생성할 수 있어야 한다. 원문 일기 텍스트는 민감정보이므로 공개 재현 패키지에 포함하지 않는다. 대신 사전 정의한 변환 규칙과 비식별 요약 변수를 제공한다.`, `<div class="note"><strong>AI와 연구자의 판단 3줄</strong><br>AI는 문헌 구조화, 다국어 웹 표현 및 코드 초안을 도왔다.<br>연구자는 연구문제, 측정 기준, 인과 해석의 한계와 안전 원칙을 결정한다.<br>실제 데이터와 결론은 수집·검증 후에만 추가하며, AI가 생성한 수치로 대체하지 않는다.</div>`]}
  ]
};
const en = {title:'Does Daily Positive Reflection Affect Next-Day Self-Efficacy?',subtitle:'A literature review and protocol for a 14-day repeated-measures study with university students',pages:[]};
const enText=[
['Abstract',`This paper presents a literature review and a preregistered protocol for examining whether a brief evening positive-reflection exercise is associated with next-day state self-efficacy. Positive psychology interventions have shown small average benefits for well-being, yet daily within-person mechanisms remain underexamined. Participants will record three events that went well and why they occurred; the next morning they will rate confidence in beginning and sustaining one important task.`,`No empirical results are claimed here. The document specifies a reproducible procedure, measures, analysis plan, ethical safeguards, and an MVP design so that a later study can replace the planned-results section with verified findings.`],
['Keywords and scope',`Keywords: positive reflection; Three Good Things; gratitude; self-efficacy; daily diary; repeated measures; digital mental health. This is not a diagnostic or treatment app protocol. It investigates a low-risk self-observation practice.`,`Self-efficacy means a person’s judgment that they can organize and execute actions required in a particular situation (Bandura, 1997). It is therefore distinct from merely feeling good. Positive reflection is defined here as structured writing about events, context, one’s own contribution, and others’ help.`],
['1. Background',`Negative events often capture attention and repetitive rumination can hinder recovery and task initiation. The broaden-and-build account proposes that positive emotions may expand momentary thought-action repertoires and help build enduring resources (Fredrickson, 2001).`,`A useful study question must specify who records what, when, and which observable outcome changes. This protocol fixes the temporal order: a three-minute evening reflection followed by next-morning task confidence. The student sample is practical for repeated mobile entries, but is not representative of all students or clinical populations.`],
['2. Prior research: gratitude and positive psychology interventions',`Emmons and McCullough (2003) compared gratitude listings with hassles and control listings and reported better outcomes on several, not all, well-being measures in gratitude conditions. Seligman and colleagues (2005) tested interventions including Three Good Things in an online randomized study.`,`A meta-analysis by Sin and Lyubomirsky (2009) found average improvements in well-being and depressive symptoms across positive psychology interventions, while also underscoring heterogeneity. Existing evidence is promising, not a guarantee that every individual benefits identically. This protocol prioritizes a within-person question: what happens after a participant has a more complete reflection than usual?`],
['3. Prior research: self-efficacy and reflection',`Bandura identified mastery experience, vicarious experience, verbal persuasion, and physiological or affective states as major sources of self-efficacy. Reflecting on small accomplishments and connecting them to actions may make mastery information more accessible; this is a hypothesis, not proof that journaling creates success.`,`Free writing can be burdensome or become rumination. The prompt therefore asks both “What went well?” and “What helped make it possible?” without inducing social comparison or performance scoring. State self-efficacy is measured for one next-day task to align the construct with the app’s practical purpose.`],
['4. Conceptual model and research questions',`The proposed pathway is evening positive reflection → accessibility of positive experience and perceived personal contribution → next-morning task self-efficacy. Prior affect, expected task difficulty, and sleep may influence both reflection and confidence and are recorded as covariates.`,`RQ1 asks whether next-day self-efficacy is higher after a completed reflection. RQ2 asks whether specificity and perceived self-contribution relate to confidence. RQ3 asks whether associations remain after covariates. H1 predicts higher next-day state self-efficacy within the same participant after reflection. A null or negative coefficient, or an interval inconsistent with a meaningful difference, does not support H1.`],
['5. Study design',`This is a 14-day single-group repeated-measures observational study. It is designed to establish feasibility, adherence, and within-person association before any causal app claim. A randomized controlled design would be needed for a strong causal conclusion.`,`Twenty convenience-sampled university students aged 18 or older are targeted. Participants complete evening entries on days 1–14 and next-morning surveys. The primary analysis includes participants with at least ten paired days. Missing values are not invented or imputed without a prespecified justification; their pattern is reported.`],
['6. Procedure and measures',`Between 20:00 and 02:00, the app asks participants to write three things that went well or were appreciated, each with a brief explanation of why. Tags may indicate others’ help, one’s own action, or circumstance. Completion time and item count are recorded.`,`Between 05:00 and 12:00, participants name one important task and rate confidence in starting and continuing it from 0 to 10. They also rate positive and negative affect, expected task difficulty, and prior-night sleep duration. The primary outcome is next-day state self-efficacy; the brief single item minimizes burden but limits psychometric breadth.`],
['7. Data management and analysis plan',`Data use randomized participant codes. Names, precise location, and unnecessary third-party identifiers are not collected. Raw text is separately encrypted after de-identification review; analytic data retain only prespecified derivatives such as length, tags, and specificity score.`,`Reflection completion is defined before analysis as at least two completed items. Two independent coders score specificity (0 abstract; 1 concrete event; 2 event plus explanation) under a fixed codebook and report agreement. A linear mixed model predicts next-day self-efficacy with participant random intercepts and reflection, deviation from a participant’s usual completion, prior affect, task difficulty, and sleep as fixed effects. Coefficients, 95% intervals, and individual trajectories are reported together.`],
['8. Preregistered result-reporting format',`No findings are inserted before data collection. The final report will show adherence as completed/requested days; individual means, ranges, and time series for self-efficacy; mixed-model coefficients with 95% intervals; and missing entries by time point and reason.`,`A non-supportive result remains informative. Low adherence may first indicate friction in the recording experience rather than absence of a psychological association. Conversely, an observed association cannot establish causation in this non-randomized design.`],
['9. Ethics and risk management',`A positive exercise can still feel pressuring on a difficult day. The app includes a skip option and neutral wording that it is acceptable not to record. It avoids streaks, rankings, and repeated nudges.`,`Consent explains purpose, collected fields, retention, withdrawal, and that the app is not diagnosis or crisis care. Immediate self-harm or harm-to-others expressions are not handled by automation alone; the interface directs users to local emergency and counselling resources. On-device storage is the default for an MVP; any cloud or AI feature requires explicit disclosure, encryption, deletion controls, and user choice.`],
['10. Translating the protocol into an app',`The product should preserve the measured flow rather than become a chatbot that promises happiness. The first screen shows only evening reflection, morning check-in, and today’s completion state.`,`A sufficient MVP has five functions: evening entries, morning efficacy slider, a local weekly trend chart, CSV export, and language switching. The chart shows observations and missingness; it does not infer that the app improved a user’s mental health. Any later AI assistance should only suggest editable tags and must not silently transmit diary text.`],
['11. Expected contribution and limitations',`The contribution is a small, reproducible protocol linking brief mobile reflection and state self-efficacy in temporal order while reporting adherence, specificity, and missingness. It also identifies minimal safety and transparency requirements for a self-recording app.`,`Limitations include convenience sampling, small sample size, self-report and common-method bias, the non-randomized design, a single-item outcome, and cultural variation in how positive events are interpreted. A next study could randomize event-only versus event-plus-cause prompts and add behavioral timestamps for task initiation.`],
['12. Conclusion',`Positive reflection should not be treated as a vague instruction to think positively. It is an observable behavior whose timing, content, burden, and interpretation can be examined. This protocol asks whether recording positive events and their causes covaries with next-day confidence to begin an important task.`,`The defensible conclusion at this stage is not that the exercise works, but that the question can be tested with transparent measures, analysis, and safeguards. Only collected and verified data can determine whether the hypothesis is supported.`]
];
en.pages=[{type:'cover'},...enText.map(([h,...p])=>({h,p})),{h:'References',p:['The following sources were verified by author, title, year, venue, and DOI or an official bibliographic record.'],refs:ko.pages[15].refs},{h:'Appendix A. Reproducibility package',p:['The package should include de-identified CSV data, a data dictionary, analysis script, codebook, manuscript PDF, and change log. Each row represents one participant at one time point. Raw diary text should not be included in a public package.','AI assisted with literature organization, bilingual web presentation, and a code draft. The researcher determines the research question, measurement criteria, limits of causal interpretation, and safety principles. Actual data and conclusions are added only after collection and verification.']}];
function render(lang){const d=lang==='en'?en:ko;document.documentElement.lang=lang;document.title=d.title;const pages=d.pages.map((s,i)=>{if(s.type==='cover')return `<section class="page cover"><div class="eyebrow">Literature review · research protocol</div><h1>${d.title}</h1><p class="subtitle">${d.subtitle}</p><div class="meta">Author: [Name] · Date: 2026. 09. 14<br>Web paper edition · Version 1.0</div></section>`;const refs=s.refs?`<div>${s.refs.map(r=>`<p class="ref">${r}</p>`).join('')}</div>`:'';return `<article class="page"><h2>${s.h}</h2>${s.p.map((p,j)=>j===0?`<p class="lead">${p}</p>`:`<p>${p}</p>`).join('')}${refs}</article>`}).join('');document.querySelector('#paper').innerHTML=pages;document.querySelector('#lang').textContent=lang==='ko'?'English':'한국어';document.querySelector('#lang').setAttribute('aria-label',lang==='ko'?'영어로 전환':'Switch to Korean');}
let language='ko';render(language);document.querySelector('#lang').addEventListener('click',()=>{language=language==='ko'?'en':'ko';render(language)});document.querySelector('#print').addEventListener('click',()=>window.print());
